### ISSUE TITLE
Failed to detect capture rect!

### ISSUE THREAD

**Issue by taichifox95** [coolwill/qr-tunnel#1]
你好，我在用MacOS Catlina上JDK1.8环境下的Receiver，RD上是VMWare链接的Win10 JDK1.8，显示Failed to detect capture rect!。

**Comment by coolwill** [comment]
请确保在点击Start按钮时，虚拟机里面的SenderForm整个窗口没有被遮挡，边上的白色部分也不能被遮住。

**Comment by taichifox95** [comment]
谢谢回复！我按照说明按步执行，Receiver为win10环境时可以用，Receiver为MacOS时不可用。

**Comment by coolwill** [comment]
这里有个测试屏幕截图的程序，先解压出来。
然后按照原来的步骤执行，到点击ReciverForm里面的Start按钮这一步时，执行截图程序，会在同目录下生成screenshot.jpg，传上来看看有什么问题
[test-screenshot.zip](https://github.com/coolwill/qr-tunnel/files/5573978/test-screenshot.zip)

**Comment by IsQiao** [comment]
如果失败，尝试降低屏幕分辨率即可
