### ISSUE TITLE
可以开发安卓端接受文件吗？

### ISSUE THREAD

**Issue by miyouzi** [coolwill/qr-tunnel#2]
用于拷贝出隔离网电脑的文件

**Comment by coolwill** [comment]
很遗憾并没有这个打算。以下简述两点：
1.用相机录制显示器画面时很容易产生干扰条纹，影响识别成功率。对于本程序来说，识别率是非常关键的，因为是单向传输，发送端无法获知传输是否成功。
2.手机即使用支架固定在桌子上，还是会因为震动/气流等造成微小抖动，从而使录制画面中的二维码的位置产生偏差。这导致本程序用来优化识别速度和传输速度的一些方案无法在手机上实行。

**Comment by meiMingle** [comment]
https://github.com/divan/txqr
https://divan.dev/posts/fountaincodes/
https://en.wikipedia.org/wiki/Fountain_code
也许这可以为此提供理论支持

**Comment by coolwill** [comment]
当然，用手机扫二维码本来就是会晃动，也不会因此而扫不出来。我的意思是，在这种情况下不能直接裁切出二维码区域从而提升识别速度，然而本程序的主要特点就是通过定位和裁切二维码来提升识别速度进而提升传输速度。
